name: builder
on: push
jobs:
  generator:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
      buildx: ${{ steps.generate-buildx.outputs.buildx }}
      tags: ${{ steps.generate-tags.outputs.tags }}
      test-images: ${{ steps.generate-test-images.outputs.test-images }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        check-latest: true
    - name: Fetch Dependencies
      run: sudo apt install -qq -y jq && npm install
    - name: Generate Container Build Info
      run: node generator bitmeal/nodegit --node-versions 1 --nodegit-versions 1 > manifest.json
    - name: Export Build Matrix
      id: generate-matrix
      run: echo "::set-output name=matrix::$(jq -c '.matrix' manifest.json)"
    - id: generate-buildx
      run: echo "::set-output name=buildx::$(jq -c '.buildx' manifest.json)"
    - id: generate-tags
      run: echo "::set-output name=tags::$(jq -c '.tags' manifest.json)"
    - id: generate-test-images
      run: echo "::set-output name=test-images::$(jq -c '."test-images"' manifest.json)"
  
  image-builder:
    needs: generator
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.generator.outputs.matrix)}}
      fail-fast: false
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_TOKEN }}
        password: ${{ secrets.DOCKER_HUB_SECRET }}
    - uses: actions/checkout@v2
    - name: Fetch Dependencies
      run: sudo apt install -qq -y jq
    - name: Build local testing Image
      run: |
        IMAGE="$(echo '${{needs.generator.outputs.test-images}}' | jq -r '."${{matrix.image}}"."${{matrix.nodegit}}"')" && 
        docker buildx build --load --build-arg ALPINE_TAG=${{matrix.image}} --build-arg NODEGIT_VERSION=${{matrix.nodegit}} --tag ${IMAGE} .
    - name: Check Nodegit Version
      run: |
        IMAGE="$(echo '${{needs.generator.outputs.test-images}}' | jq -r '."${{matrix.image}}"."${{matrix.nodegit}}"')" && 
        NODEGIT="$(docker run --rm $IMAGE /usr/local/bin/npm -g ls | grep '^\+.*\snodegit@' | grep -oP '(\d+\.){2}\d+')" && echo "nodegit versions: ${NODEGIT}"
        [ "$NODEGIT" == "${{matrix.nodegit}}" ] && 
        echo "nodegit versions @${{matrix.nodegit}} [ OK ]"
    - name: Test Nodegit
      run: |
        IMAGE="$(echo '${{needs.generator.outputs.test-images}}' | jq -r '."${{matrix.image}}"."${{matrix.nodegit}}"')" && 
        docker run --rm -v "$(pwd)/test":/test $IMAGE /bin/ash -c "cp -r /test ~/test && cd ~/test && chmod +x init.sh && ./init.sh && echo using: && cat package.json && npm install && node test.js"
    - name: Build and push multiarch Images
      run: docker buildx build  --push --build-arg ALPINE_TAG=${{matrix.image}} --build-arg NODEGIT_VERSION=${{matrix.nodegit}} --platform "linux/amd64,linux/arm64" $(echo '${{needs.generator.outputs.buildx}}' | jq -r '."${{matrix.image}}"."${{matrix.nodegit}}"') .

    - name: Prepare status artifact @SUCCESS
      if: ${{ success() }}
      run: |
        echo '{"success": true, "image": "${{matrix.image}}", "nodegit": "${{matrix.nodegit}}"}' | jq '.' > ${{matrix.image}}@${{matrix.nodegit}}.json
    - name: Prepare status artifact @FAILURE
      if: ${{ failure() }}
      run: |
        echo '{"success": false, "image": "${{matrix.image}}", "nodegit": "${{matrix.nodegit}}"}' | jq '.' > ${{matrix.image}}@${{matrix.nodegit}}.json
    - name: Upload status artifact [${{matrix.image}}@${{matrix.nodegit}}.json]
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.image}}@${{matrix.nodegit}}.json
        path: ${{matrix.image}}@${{matrix.nodegit}}.json

  chronicler:
    needs:
      - generator
      - image-builder
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch Dependencies
      run: sudo apt install -qq -y jq
    - name: Show tags passed from generator
      run: echo '${{needs.generator.outputs.tags}}' | jq '.'
    - name: Fetch matrix jobs status artifacts
      uses: actions/download-artifact@v2
      with:
        path: jobs
    - name: Display status artifacts layout
      run: ls -R
      working-directory: jobs